### ISSUE TITLE
Balance without VAT NaN

### ISSUE THREAD

**Issue by persand** [urre/fruitage#1]
I'm getting NaN on the "Balance without VAT" on the following pages:

/reports
/reports/uninvoiced
/invoices/archive

See attached screenshot for number format settings

![screenshot 2016-01-19 10 21 40](https://cloud.githubusercontent.com/assets/63389/12414581/a5db9fde-be96-11e5-87d1-eea2733fdcb6.png)

![screenshot 2016-01-19 10 23 29](https://cloud.githubusercontent.com/assets/63389/12414591/b25eb0de-be96-11e5-9de7-c6c002a8b41e.png)

![screenshot 2016-01-19 10 23 47](https://cloud.githubusercontent.com/assets/63389/12414598/bd6f7904-be96-11e5-84fd-3dcd52e41977.png)

![screenshot 2016-01-19 10 25 18](https://cloud.githubusercontent.com/assets/63389/12414638/0ac3acf2-be97-11e5-868d-a32611d77776.png)

**Comment by urre** [comment]
@persand hm, does it work in the other pages? do you use SEK as currency all over?

**Comment by urre** [comment]
@persand what's your currency format?

**Comment by persand** [comment]
@urre Yes it works on the other pages.

Currency info:

<img width="788" alt="screenshot 2016-01-19 20 56 37" src="https://cloud.githubusercontent.com/assets/63389/12430285/27a65be6-beef-11e5-84ac-83063bb4a262.png">

**Comment by urre** [comment]
@persand thanks, i will look into it now!

**Comment by urre** [comment]
@persand [1.2.1](https://github.com/urre/fruitage/releases/tag/v1.2.1) is out with fixes! Please try the latest version and let me know if you have any issues. It should support all currency formats now.

PS. /invoices/archive is not supported (yet)

**Comment by urre** [comment]
@persand [1.2.2](https://github.com/urre/fruitage/releases/tag/v1.2.2) out, now without node_modules :)

**Comment by persand** [comment]
@urre works like a charm! 👌

**Comment by urre** [comment]
@persand sweet :+1:
